site_name: AukletAPM To Go Documentation
theme: material

pages:
    - AukletAPM To Go: index.md
    - Getting started:  getting-started/index.md
    - Java & servlet integration:  getting-started/java-servlet-integration.md
    - Kotlin & servlet integration:  getting-started/kotlin-servlet-integration.md
    #- Getting started:
    #- Tutorials:
      #- Showing JVM system properties (Java): index.md
      #- Showing OS information (Java): index.md
      #- Showing server root space (Java): index.md
      #- Using metrics & logback to track log on the go (Kotlin): index.md

#repo_name: 'aukletapm/aukletapm-to-go-doc'
#repo_url: 'https://github.com/aukletapm/aukletapm-to-go-doc'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/aukletapm'

google_analytics:
    - 'UA-115889724-1'
    - 'auto'
copyright: 'Coded with ❤ in Shanghai | Version:1.3.2'

markdown_extensions:
  - codehilite
